### ISSUE TITLE
[PE-D][Tester D] Report "User already exists" only after keying in the password

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#140]
![image.png](https://raw.githubusercontent.com/vvhuiling/ped/main/files/941f5cc4-93dd-4f2f-9538-9c56ff518dba.png)
Reporting right after keying in the username maybe better

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: vvhuiling/ped#2

**Comment by TeoHaoZhi** [comment]
response.rejected - Hao Zhi

Does not break user experience
