### ISSUE TITLE
[PE-D][Tester B] Ambiguity in login process

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#142]
![Screenshot 2023-11-03 at 4.43.37 PM.png](https://raw.githubusercontent.com/ken-ruster/ped/main/files/4f8797f0-fbe6-4bd5-a49f-335328036894.png)

Formatting makes it so it is not immediately obvious how to log into the application. Highlighting what to enter using a code block or adding an example would. be immensely helpful.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ken-ruster/ped#5

**Comment by TeoHaoZhi** [comment]
response.accept- Hao Zhi

Thank you for the feedback, changes has been made
