### ISSUE TITLE
[PE-D][Tester D] copy paste Command from UG is invalid

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-3/tp#144]
![image.png](https://raw.githubusercontent.com/vvhuiling/ped/main/files/b90ca323-d187-471a-88e3-d523553f20db.png)

![image.png](https://raw.githubusercontent.com/vvhuiling/ped/main/files/3e110ae5-0de3-490c-97bd-2d1bc587fc14.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: vvhuiling/ped#3

**Comment by TeoHaoZhi** [comment]
response.accept - Hao Zhi

Duplicate with issue #149
