### ISSUE TITLE
[PE-D][Tester E] Bug with add command Cant add according to sample input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#154]
![image.png](https://raw.githubusercontent.com/wwweert123/ped/main/files/1e650f37-d6bc-4aed-a188-417055289e83.png)

![image.png](https://raw.githubusercontent.com/wwweert123/ped/main/files/d6af51fa-e344-43a0-bb3f-626e9c719923.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wwweert123/ped#4

**Comment by martinschnder** [comment]
Updated userguide to match actual behaviour
