### ISSUE TITLE
[PE-D][Tester B] Password not hidden during login and registration

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#158]
![Screenshot 2023-11-03 at 5.00.12 PM.png](https://raw.githubusercontent.com/ken-ruster/ped/main/files/d5bb2935-efd9-4bd2-be2b-a512024bd48f.png)

Might cause some privacy and security issues, considering the clearance needed to handle certain drugs. Might make it easier for bad actors to manipulate records.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ken-ruster/ped#9

**Comment by TeoHaoZhi** [comment]
reponse.rejected- Hao Zhi

Nitpicking, will mask away input in future iterations

Nonetheless issue will be mentioned in user guide
