### ISSUE TITLE
[PE-D][Tester D] Can't delete input as the UG described

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-3/tp#160]
![image.png](https://raw.githubusercontent.com/vvhuiling/ped/main/files/f00a82da-43f1-4503-acb8-e7cc27dd8262.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: vvhuiling/ped#9

**Comment by martinschnder** [comment]
Fixed by updating the regex
