### ISSUE TITLE
[PE-D][Tester C] Negative Quantity not caught

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#173]
![bug 2.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/399ca312-5bc4-4541-a6f1-41d66dc77493.jpg)
### 

Negative values for drug quantity not caught

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: spinoandraptos/ped#2

**Comment by martinschnder** [comment]
added positive integer verification
