### ISSUE TITLE
[PE-D][Tester C] Registering with a space not caught

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#175]
![bug 3.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/272a0b46-18a9-4bc7-b102-9052987129b9.jpg)

Registering new account using space for either username or password not caught.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: spinoandraptos/ped#3

**Comment by TeoHaoZhi** [comment]
response.rejected- Hao Zhi

Duplicate issue with logging in with space character, nonetheless fixed with trim()
