### ISSUE TITLE
[PE-D][Tester C] Logging in with space not caught

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-3/tp#178]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![bug 6.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/5727d260-9812-4d5f-a7ca-ac3df31f7e87.jpg)

Logging in using single space for username and password not caught

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: spinoandraptos/ped#5

**Comment by TeoHaoZhi** [comment]
reponse.rejected - Hao Zhi

Spacebar is a legitamate character in making a string, nonetheless issue fixed with trim()
