### ISSUE TITLE
[PE-D][Tester C] Login with trailing space not valid 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-3/tp#179]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![bug 7.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/4a007500-89e3-4e06-8420-636e0fc5c2ad.jpg)

Login with a trailing space not recognised as a valid command, can be hard to spot for users who accidentally added a space behind and lead to poor user experience. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: spinoandraptos/ped#6

**Comment by TeoHaoZhi** [comment]
response.Accepted - Hao Zhi

feels like nitpicking, nonetheless fixed with trim()
