### ISSUE TITLE
[PE-D][Tester C] Register with trailing space not valid

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#182]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![bug 8.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/fd5a1bd0-0429-409d-987d-8f8172c4e329.jpg)

Register with a trailing space not recognised as a valid command, can cause confusion to users who accidentally add a trailing space

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: spinoandraptos/ped#7

**Comment by TeoHaoZhi** [comment]
reponse.Accepted- Hao Zhi

feels like nitpicking, but accepted and fixed with trim() nonetheless
