### ISSUE TITLE
[PE-D][Tester C] Unhandled Invalid int exception 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#190]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![bug 14.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/ea3337c4-f487-421e-bc03-e349eaaf77d9.jpg)

Passing a non-integer value to addotcart crashes the program

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: spinoandraptos/ped#11

**Comment by martinschnder** [comment]
Added exception handling !
