### ISSUE TITLE
[PE-D][Tester B] Save command is unnecessary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#191]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
While a manual save function is provided, the program automatically saves data after each command, making the manual save function unnecessary.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ken-ruster/ped#18

**Comment by TeoHaoZhi** [comment]
Save command is a feature, not quite sure what tester means by program saves data after each command. No example given,

response.IssueUnclear
