### ISSUE TITLE
[PE-D][Tester C] Adding negative quantities to cart not handled

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#194]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![bug 16.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/626c5da7-7121-44c4-b9ea-0c121743e71f.jpg)

Adding negative quantities of drug to cart not handled

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: spinoandraptos/ped#13

**Comment by martinschnder** [comment]
Fixed by verifying the quantity
