### ISSUE TITLE
[PE-D][Tester C] Adding to cart with quantity equal to stock quantity not allowed

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#195]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![bug 17.jpg](https://raw.githubusercontent.com/spinoandraptos/ped/main/files/992844cc-11a1-47ca-9186-9d9f33de9826.jpg)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: spinoandraptos/ped#14

**Comment by martinschnder** [comment]
Fixed !
