### ISSUE TITLE
[PE-D][Tester A] Uncaught NumberFormatException in addtocart command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#205]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
If the user enters anything other than numbers for the addtocart command (e.g. `addtocart /n panadol /q a`, the program throws a NumberFormatException and exits

![image.png](https://raw.githubusercontent.com/hooami/ped/main/files/ac5bf52c-08fd-46f2-a062-c0f2ce563270.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: hooami/ped#8

**Comment by martinschnder** [comment]
bug fixed by catching the exception
